# Pratical Questions
#### Date: 5th October 2024

### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.



In [3]:
import numpy as np

np.random.randint(0,100, (3,3))

array([[23, 86, 48],
       [69, 31, 19],
       [65, 63,  0]], dtype=int32)

### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [18]:
new_shape = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)

print('here is the 2x5 array :')

print(new_shape)

print('here is the 5x2array :')

print(new_shape.reshape(5,2))

here is the 2x5 array :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
here is the 5x2array :
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [189]:
random_float_value = np.random.rand(4,4)
border_zeros = np.zeros((6,6))

border_zeros[1][1:5] = random_float_value[0]
border_zeros[2][1:5] = random_float_value[1]
border_zeros[3][1:5] = random_float_value[2]
border_zeros[4][1:5] = random_float_value[3]

border_zeros

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.88811021, 0.00583069, 0.12422696, 0.87220825,
        0.        ],
       [0.        , 0.00955088, 0.66585598, 0.33793321, 0.58795765,
        0.        ],
       [0.        , 0.40686247, 0.29063872, 0.14511431, 0.77127629,
        0.        ],
       [0.        , 0.2981468 , 0.34705594, 0.33119682, 0.12586093,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [41]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [50]:
string_value = np.array(['python', 'numpy', 'pandas'])

print(np.char.upper(string_value), 'in uper transformations...')
print(np.char.lower(string_value), 'in lower transformations..')
print(np.char.title(string_value), 'in title transformations..')

['PYTHON' 'NUMPY' 'PANDAS'] in uper transformations...
['python' 'numpy' 'pandas'] in lower transformations..
['Python' 'Numpy' 'Pandas'] in title transformations..


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [91]:
string_value = np.array(['python', 'numpy', 'pandas'])
np.char.join('  ,  ',string_value)

array(['p  ,  y  ,  t  ,  h  ,  o  ,  n', 'n  ,  u  ,  m  ,  p  ,  y',
       'p  ,  a  ,  n  ,  d  ,  a  ,  s'], dtype='<U31')

### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.



In [93]:
arr1 = np.random.randint(1,10,(4,4))
arr2 = np.random.randint(1,10,(4,4))

print(arr1)
print(arr2)

print(arr1 + arr2, 'this is addition')
print(arr1 - arr2, 'this is substraction')
print(arr1 * arr2, 'this is multiplicaton')
print(arr1 / arr2, 'this is division')
print(arr1 @ arr2, 'this is matrix multiplication')

[[9 4 7 3]
 [6 2 7 1]
 [8 5 4 7]
 [1 6 8 2]]
[[2 4 2 9]
 [6 6 4 9]
 [2 1 3 9]
 [8 9 4 6]]
[[11  8  9 12]
 [12  8 11 10]
 [10  6  7 16]
 [ 9 15 12  8]] this is addition
[[ 7  0  5 -6]
 [ 0 -4  3 -8]
 [ 6  4  1 -2]
 [-7 -3  4 -4]] this is substraction
[[18 16 14 27]
 [36 12 28  9]
 [16  5 12 63]
 [ 8 54 32 12]] this is multiplicaton
[[4.5        1.         3.5        0.33333333]
 [1.         0.33333333 1.75       0.11111111]
 [4.         5.         1.33333333 0.77777778]
 [0.125      0.66666667 2.         0.33333333]] this is division
[[ 80  94  67 198]
 [ 46  52  45 141]
 [110 129  76 195]
 [ 70  66  58 147]] this is matrix multiplication


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [43]:
a = np.eye(5)

print(a)

result = np.extract(np.eye(5), a)

print(result, 'this is the extract version of the above identity array')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.] this is the extract version of the above identity array


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [146]:
#len(np.random.randint(0,1000,(100)))


def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

convert_boolean_elementwise = np.vectorize(is_prime)

random_integer_array = np.random.randint(0, 1000, 100)

find_prime_from_random_integer_array = convert_boolean_elementwise(random_integer_array)

result = random_integer_array[find_prime_from_random_integer_array]

result

array([367, 619, 359,  19, 547, 853, 439, 157, 191, 281, 647, 811,  47],
      dtype=int32)

### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [171]:
daily_temperatures = np.random.uniform(28, 50, size=30)

print('Daily temp the month',daily_temperatures)

# weekly_temperatures = daily_temperatures.reshape(4, 7)
weekly_temperatures = daily_temperatures.reshape(5, 6)

print('weekly temp of the month in 5week 6day basic',weekly_temperatures)

mean_temp = weekly_temperatures.mean()

print('here is the weekly avg temp for this month', mean_temp)

Daily temp the month [48.70663515 45.49260235 42.37830808 28.47404854 39.46080021 37.78392013
 46.46385114 34.1921819  36.46659575 35.44981302 31.90501935 28.07336318
 31.3018116  29.67374477 49.10099094 41.63875139 41.130672   36.37803761
 49.39749435 41.02241592 28.66886968 41.2650847  32.17956594 46.92049116
 45.29116396 37.60656001 49.9208251  43.39523579 28.14174768 30.10513536]
weekly temp of the month in 5week 6day basic [[48.70663515 45.49260235 42.37830808 28.47404854 39.46080021 37.78392013]
 [46.46385114 34.1921819  36.46659575 35.44981302 31.90501935 28.07336318]
 [31.3018116  29.67374477 49.10099094 41.63875139 41.130672   36.37803761]
 [49.39749435 41.02241592 28.66886968 41.2650847  32.17956594 46.92049116]
 [45.29116396 37.60656001 49.9208251  43.39523579 28.14174768 30.10513536]]
here is the weekly avg temp for this month 38.59952455825697
